Working on modal service
bepotts/airbnb_clone pull request #7
Opened 2022-04-18 12:30 UTC by matttm

It opens, and work hqs to be done for cloise
![Uploading Screen Shot 2022-04-18 at 8.28.26 AM.png…]()

2022-04-18 13:46 UTC, bepotts commented on public/index.html
> +  <div id="portal-container"></div>
There's really only supposed to be one "root" div for React per page. The file [index.js](https://github.com/bepotts/airbnb_clone/blob/master/index.js) contains the root React render, and "App.js" in [sources/App.js](https://github.com/bepotts/airbnb_clone/blob/master/source/App.js) contains the application that most of the stuff should be thrown into. 

This div should be deleted and the Component that it's rendering should be added there.

2022-04-18 14:07 UTC, bepotts commented on source/services/ModalService/ModalService.js
> +        const node = document.createElement('div');
Why are you creating a singular div and then rendering on it? Is this needed for multiple model renderings?

2022-04-18 14:09 UTC, bepotts commented on source/services/ModalService/ModalService.js
> +    const container = document.querySelector('#portal-container');
If you're querying for an ID, you might as well use `Document.getElementById` instead of querySelector.

2022-04-18 14:10 UTC, bepotts requested changes
Made some more specific comments, but model is spelt with an "e" not an "a".  Unless I'm missing something, you should correct the spelling in all the "modal" locations.

2022-04-18 14:28 UTC, matttm commented on public/index.html
> +  <div id="portal-container"></div>
Right, but if you want it to be rendered outside of the root component, like how a modal, is, you'd need somethin g else to append it to.

2022-04-18 14:29 UTC, matttm commented on source/services/ModalService/ModalService.js
> +        const node = document.createElement('div');
I was initially writing it for that, but decided not to when I was unning into difficulty. I can change this.

2022-04-18 14:34 UTC, matttm commented
> Made some more specific comments, but model is spelt with an "e" not an "a". Unless I'm missing something, you should correct the spelling in all the "modal" locations.

I used an "a" on purpose. Afaik, the popup is a modal

https://www.google.com/search?q=modal+box+css&rlz=1C5GCEM_en&oq=modal&aqs=chrome.0.69i59j69i57j69i59j69i61l2j69i60.2938j0j7&sourceid=chrome&ie=UTF-8

2022-04-18 14:57 UTC, matttm commented on source/services/ModalService/ModalService.js
> +    const container = document.querySelector('#portal-container');
I can do that

2022-04-24 15:08 UTC, bepotts approved these changes

2022-04-24 15:08 UTC, merged

2024-04-27 06:11 UTC, closerhan commented
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mhmmdirwn, @canraababy, @MichaelTen, @dasterdly, @7HIEN, @mohsen-in, @godugome, @anyuechao, @titlelevor, @kiok46, @rajatdutta05, @gerry-wang-intelematics, @Nucnay3428, @Pond99, @angelsenvy, @thimslugga, @djdexter84, @tambnice, @nicsu82, @armchanachai, @baby636, @robocups, @mohamedosama914, @AllanRey01, @jinsongbo, @sagech, @ComGreed, @miccomservices, @namvuhoai, @brtirfan, @ChinaVolvocars, @tephyrnex, @KonradIT, @consensyx, @mission-bitcoin, @itworkco, @joneldiablo, @satarii, @clemlesne, @edud69, @jtrag, @chiemekailo, @HeminWon, @bepotts, @Benni13, @ArnonHongklay, @federerfanatic, @leejw51, @arrebagrove, @crackings

2024-04-27 06:21 UTC, closerhan commented
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!